import Head from 'next/head';
import MainFooter from 'components/MainFooter';
import styles from '../styles/home.module.scss';
import InnovationSection from '../components/homepage/InnovationSection';
import ServicesSection from '../components/homepage/ServicesSection';
import AboutUsSection from '../components/homepage/AboutUsSection';
import CreativitySection from '../components/homepage/CreativitySection';
import BuildSection from '../components/homepage/BuildSection';
import FeedBackSection from '../components/homepage/FeedBackSection';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Obiala</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <InnovationSection />
        <ServicesSection />
        <AboutUsSection />
        <CreativitySection />
        <BuildSection />
        <FeedBackSection />
        <MainFooter />
      </main>
    </div>
  );
}
